import 'entities/project.dart';

/// Stub data — replace with repository call when API is ready.
class MockProjects {
  MockProjects._();

  static const List<Project> myProjects = [
    Project(
      id: 'p1',
      name: 'Europe Trip 2025',
      category: ProjectCategory.vacations,
      status: ProjectStatus.ongoing,
      relation: ProjectRelation.owned,
      goalAmount: 5000,
      currentAmount: 2700,
      endsIn: '2 months',
    ),
    Project(
      id: 'p2',
      name: 'Investment',
      category: ProjectCategory.investment,
      status: ProjectStatus.completed,
      relation: ProjectRelation.owned,
      currentAmount: 7600,
    ),
    Project(
      id: 'p3',
      name: 'Emergency Fund',
      category: ProjectCategory.emergency,
      status: ProjectStatus.completed,
      relation: ProjectRelation.owned,
      currentAmount: 5000,
    ),
    Project(
      id: 'p8',
      name: 'Investment',
      category: ProjectCategory.investment,
      status: ProjectStatus.ongoing,
      relation: ProjectRelation.owned,
      goalAmount: 8000,
      currentAmount: 3200,
      endsIn: '4 months',
      description: 'e.g. Long-term growth contribution pot',
    ),
  ];

  static const List<Project> joinedProjects = [
    Project(
      id: 'p4',
      name: 'Europe Trip 2025',
      category: ProjectCategory.vacations,
      status: ProjectStatus.ongoing,
      relation: ProjectRelation.joined,
      goalAmount: 5000,
      currentAmount: 2700,
      endsIn: '2 months',
      description: 'e.g. Summer vacation across France and Italy',
    ),
    Project(
      id: 'p5',
      name: 'Investment',
      category: ProjectCategory.investment,
      status: ProjectStatus.completed,
      relation: ProjectRelation.joined,
      currentAmount: 5000,
    ),
    Project(
      id: 'p6',
      name: 'Emergency Support Pot',
      category: ProjectCategory.emergency,
      status: ProjectStatus.ongoing,
      relation: ProjectRelation.joined,
      goalAmount: 4000,
      currentAmount: 1900,
      endsIn: '3 months',
      description: 'e.g. Medical and urgent family support pool',
    ),
    Project(
      id: 'p9',
      name: 'Investment',
      category: ProjectCategory.investment,
      status: ProjectStatus.ongoing,
      relation: ProjectRelation.joined,
      goalAmount: 7000,
      currentAmount: 2800,
      endsIn: '5 months',
      description: 'e.g. Community investment savings goal',
    ),
    Project(
      id: 'p7',
      name: 'Emergency Fund',
      category: ProjectCategory.emergency,
      status: ProjectStatus.completed,
      relation: ProjectRelation.joined,
      currentAmount: 4200,
    ),
  ];

  static const List<Project> discoverProjects = [
    Project(
      id: 'd1',
      name: 'Europe Trip 2025',
      category: ProjectCategory.vacations,
      status: ProjectStatus.ongoing,
      relation: ProjectRelation.joined,
      goalAmount: 5000,
      currentAmount: 2700,
      endsIn: '2 months',
      description: 'e.g. Summer vacation across France and Italy',
    ),
    Project(
      id: 'd2',
      name: 'Investment',
      category: ProjectCategory.investment,
      status: ProjectStatus.ongoing,
      relation: ProjectRelation.joined,
      goalAmount: 5000,
      currentAmount: 2700,
      endsIn: '2 months',
      description: 'e.g. for financial freedom (after goal pot will be close and there will only be return)',
      requestPending: true,
    ),
    Project(
      id: 'd3',
      name: 'Investment',
      category: ProjectCategory.investment,
      status: ProjectStatus.ongoing,
      relation: ProjectRelation.joined,
      goalAmount: 5000,
      currentAmount: 2700,
      endsIn: '2 months',
      description: 'e.g. for financial freedom (after goal pot will be close and there will only be return)',
    ),
    Project(
      id: 'd4',
      name: 'Europe Trip 2025',
      category: ProjectCategory.vacations,
      status: ProjectStatus.ongoing,
      relation: ProjectRelation.joined,
      goalAmount: 5000,
      currentAmount: 2700,
      endsIn: '2 months',
      description: 'e.g. Summer vacation across France and Italy',
    ),
    Project(
      id: 'd5',
      name: 'Emergency Relief',
      category: ProjectCategory.emergency,
      status: ProjectStatus.ongoing,
      relation: ProjectRelation.joined,
      goalAmount: 5000,
      currentAmount: 2700,
      endsIn: '2 months',
      description: 'e.g. Backup emergency pot for urgent needs',
    ),
    Project(
      id: 'd6',
      name: 'Completed Travel Pot',
      category: ProjectCategory.vacations,
      status: ProjectStatus.completed,
      relation: ProjectRelation.joined,
      currentAmount: 5200,
    ),
    Project(
      id: 'd7',
      name: 'Investment',
      category: ProjectCategory.investment,
      status: ProjectStatus.completed,
      relation: ProjectRelation.joined,
      currentAmount: 7600,
    ),
  ];
}
