import 'entities/project.dart';

/// Stub data — replace with repository call when API is ready.
class MockProjects {
  MockProjects._();

  static const List<Project> myProjects = [
    Project(
      id: 'p1',
      name: 'Europe Trip 2025',
      category: ProjectCategory.vacations,
      status: ProjectStatus.ongoing,
      relation: ProjectRelation.owned,
      goalAmount: 5000,
      currentAmount: 2700,
      endsIn: '2 months',
    ),
    Project(
      id: 'p2',
      name: 'Investment',
      category: ProjectCategory.investment,
      status: ProjectStatus.completed,
      relation: ProjectRelation.owned,
      currentAmount: 7600,
    ),
    Project(
      id: 'p3',
      name: 'Emergency Fund',
      category: ProjectCategory.emergency,
      status: ProjectStatus.completed,
      relation: ProjectRelation.owned,
      currentAmount: 5000,
    ),
    Project(
      id: 'p8',
      name: 'Investment',
      category: ProjectCategory.investment,
      status: ProjectStatus.ongoing,
      relation: ProjectRelation.owned,
      goalAmount: 8000,
      currentAmount: 3200,
      endsIn: '4 months',
      description: 'e.g. Long-term growth contribution pot',
    ),
  ];

  static const List<Project> joinedProjects = [
    Project(
      id: 'p4',
      name: 'Europe Trip 2025',
      category: ProjectCategory.vacations,
      status: ProjectStatus.ongoing,
      relation: ProjectRelation.joined,
      goalAmount: 5000,
      currentAmount: 2700,
      endsIn: '2 months',
      description: 'e.g. Summer vacation across France and Italy',
    ),
    Project(
      id: 'p5',
      name: 'Investment',
      category: ProjectCategory.investment,
      status: ProjectStatus.completed,
      relation: ProjectRelation.joined,
      currentAmount: 5000,
    ),
    Project(
      id: 'p6',
      name: 'Emergency Support Pot',
      category: ProjectCategory.emergency,
      status: ProjectStatus.ongoing,
      relation: ProjectRelation.joined,
      goalAmount: 4000,
      currentAmount: 1900,
      endsIn: '3 months',
      description: 'e.g. Medical and urgent family support pool',
    ),
    Project(
      id: 'p9',
      name: 'Investment',
      category: ProjectCategory.investment,
      status: ProjectStatus.ongoing,
      relation: ProjectRelation.joined,
      goalAmount: 7000,
      currentAmount: 2800,
      endsIn: '5 months',
      description: 'e.g. Community investment savings goal',
    ),
    Project(
      id: 'p7',
      name: 'Emergency Fund',
      category: ProjectCategory.emergency,
      status: ProjectStatus.completed,
      relation: ProjectRelation.joined,
      currentAmount: 4200,
    ),
    // ── Demo: member user flows (tap View) — see [UserFlowOnOpen]
    Project(
      id: 'jflow-join-ok',
      name: 'Demo: Join approved (member)',
      category: ProjectCategory.vacations,
      status: ProjectStatus.ongoing,
      relation: ProjectRelation.joined,
      goalAmount: 5000,
      currentAmount: 2000,
      endsIn: '2 months',
      description: 'Opens: leader approved your join (full screen)',
      userFlow: UserFlowOnOpen.showJoinApproved,
    ),
    Project(
      id: 'jflow-join-no',
      name: 'Demo: Join rejected (member)',
      category: ProjectCategory.vacations,
      status: ProjectStatus.ongoing,
      relation: ProjectRelation.joined,
      goalAmount: 4000,
      currentAmount: 0,
      endsIn: '1 month',
      description: 'Opens: leader did not approve join',
      userFlow: UserFlowOnOpen.showJoinRejected,
    ),
    Project(
      id: 'jflow-vote',
      name: 'Demo: Success vote (member)',
      category: ProjectCategory.investment,
      status: ProjectStatus.ongoing,
      relation: ProjectRelation.joined,
      goalAmount: 5000,
      currentAmount: 4800,
      endsIn: '3 weeks',
      description: 'Opens: cast Yes/No on project success',
      userFlow: UserFlowOnOpen.showSuccessVote,
    ),
    Project(
      id: 'jflow-vote-yes',
      name: 'Demo: Mark complete — voted success',
      category: ProjectCategory.investment,
      status: ProjectStatus.ongoing,
      relation: ProjectRelation.joined,
      currentAmount: 5000,
      description: 'Skips to “Approved” feedback (mock)',
      userFlow: UserFlowOnOpen.showMarkVoteApprovedResult,
    ),
    Project(
      id: 'jflow-vote-no',
      name: 'Demo: Mark complete — voted incomplete',
      category: ProjectCategory.investment,
      status: ProjectStatus.ongoing,
      relation: ProjectRelation.joined,
      currentAmount: 5000,
      description: 'Skips to “Not Approved” feedback (mock)',
      userFlow: UserFlowOnOpen.showMarkVoteNotApprovedResult,
    ),
  ];

  static const List<Project> discoverProjects = [
    Project(
      id: 'd1',
      name: 'Europe Trip 2025',
      category: ProjectCategory.vacations,
      status: ProjectStatus.ongoing,
      relation: ProjectRelation.joined,
      goalAmount: 5000,
      currentAmount: 2700,
      endsIn: '2 months',
      description: 'e.g. Summer vacation across France and Italy',
    ),
    Project(
      id: 'd2',
      name: 'Investment',
      category: ProjectCategory.investment,
      status: ProjectStatus.ongoing,
      relation: ProjectRelation.joined,
      goalAmount: 5000,
      currentAmount: 2700,
      endsIn: '2 months',
      description: 'e.g. for financial freedom (after goal pot will be close and there will only be return)',
      requestPending: true,
    ),
    Project(
      id: 'd3',
      name: 'Investment',
      category: ProjectCategory.investment,
      status: ProjectStatus.ongoing,
      relation: ProjectRelation.joined,
      goalAmount: 5000,
      currentAmount: 2700,
      endsIn: '2 months',
      description: 'e.g. for financial freedom (after goal pot will be close and there will only be return)',
    ),
    Project(
      id: 'd4',
      name: 'Europe Trip 2025',
      category: ProjectCategory.vacations,
      status: ProjectStatus.ongoing,
      relation: ProjectRelation.joined,
      goalAmount: 5000,
      currentAmount: 2700,
      endsIn: '2 months',
      description: 'e.g. Summer vacation across France and Italy',
    ),
    Project(
      id: 'd5',
      name: 'Emergency Relief',
      category: ProjectCategory.emergency,
      status: ProjectStatus.ongoing,
      relation: ProjectRelation.joined,
      goalAmount: 5000,
      currentAmount: 2700,
      endsIn: '2 months',
      description: 'e.g. Backup emergency pot for urgent needs',
    ),
    Project(
      id: 'd6',
      name: 'Completed Travel Pot',
      category: ProjectCategory.vacations,
      status: ProjectStatus.completed,
      relation: ProjectRelation.joined,
      currentAmount: 5200,
    ),
    Project(
      id: 'd7',
      name: 'Investment',
      category: ProjectCategory.investment,
      status: ProjectStatus.completed,
      relation: ProjectRelation.joined,
      currentAmount: 7600,
    ),
    Project(
      id: 'd8',
      name: 'Demo Discover: success vote',
      category: ProjectCategory.vacations,
      status: ProjectStatus.ongoing,
      relation: ProjectRelation.joined,
      goalAmount: 6000,
      currentAmount: 4000,
      endsIn: '1 month',
      description: 'Same as jflow-vote (Discover tab)',
      userFlow: UserFlowOnOpen.showSuccessVote,
    ),
    Project(
      id: 'd9',
      name: 'Demo Discover: join approved',
      category: ProjectCategory.emergency,
      status: ProjectStatus.ongoing,
      relation: ProjectRelation.joined,
      goalAmount: 3000,
      currentAmount: 1000,
      endsIn: '6 months',
      userFlow: UserFlowOnOpen.showJoinApproved,
    ),
  ];
}
