import 'package:vestie/core/domain/entities/pagination_info.dart';
import 'package:vestie/features/project_pot/domain/entities/project_pot_entity.dart';

import 'borrow_request_entity.dart';
import 'project_announcement_entity.dart';
import 'project_detail_entity.dart';

extension ProjectDetailEntityPot on ProjectDetailEntity {
  /// Merges `GET /projects/{id}/borrow-requests` into project detail.
  ProjectDetailEntity withBorrowRequests(List<BorrowRequestEntity> requests) {
    return ProjectDetailEntity(
      id: id,
      name: name,
      category: category,
      status: status,
      goalAmount: goalAmount,
      currentAmount: currentAmount,
      totalContributed: totalContributed,
      viewerRefundAmount: viewerRefundAmount,
      contributorCount: contributorCount,
      endsIn: endsIn,
      announcement: announcement,
      announcements: announcements,
      members: members,
      borrowRequests: requests,
      viewerRole: viewerRole,
      membershipId: membershipId,
      borrowLimitAmount: borrowLimitAmount,
      repaymentWindowDays: repaymentWindowDays,
      repaymentGraceDays: repaymentGraceDays,
      contributionsAreNonRefundable: contributionsAreNonRefundable,
      displayStatusLabel: displayStatusLabel,
      projectLifecycleState: projectLifecycleState,
      projectBannerStatus: projectBannerStatus,
      votingStatus: votingStatus,
      detailUserRole: detailUserRole,
      voting: voting,
      hasWeek11ProjectDetailEnvelope: hasWeek11ProjectDetailEnvelope,
      apiCanStopContributions: apiCanStopContributions,
      borrowingEnabled: borrowingEnabled,
      pendingJoinRequestCount: pendingJoinRequestCount,
      projectInviteCode: projectInviteCode,
      roiPercentage: roiPercentage,
      joinApprovalRequired: joinApprovalRequired,
      minimumContributionAmount: minimumContributionAmount,
      penaltyPercentage: penaltyPercentage,
      successVoteWindowHours: successVoteWindowHours,
      hasActiveSuccessVote: hasActiveSuccessVote,
      activeClosureVote: activeClosureVote,
      invites: invites,
      hasCoLeader: hasCoLeader,
      coverImageUrl: coverImageUrl,
      images: images,
      membersPagination: membersPagination,
      invitesPagination: invitesPagination,
      announcementsPagination: announcementsPagination,
    );
  }

  /// Appends the next announcements page from `GET /projects/{id}`.
  ProjectDetailEntity withAppendedAnnouncements({
    required List<ProjectAnnouncementEntity> nextPage,
    required PaginationInfo pagination,
  }) {
    return ProjectDetailEntity(
      id: id,
      name: name,
      category: category,
      status: status,
      goalAmount: goalAmount,
      currentAmount: currentAmount,
      totalContributed: totalContributed,
      viewerRefundAmount: viewerRefundAmount,
      contributorCount: contributorCount,
      endsIn: endsIn,
      announcement: announcement,
      announcements: [...announcements, ...nextPage],
      members: members,
      borrowRequests: borrowRequests,
      viewerRole: viewerRole,
      membershipId: membershipId,
      borrowLimitAmount: borrowLimitAmount,
      repaymentWindowDays: repaymentWindowDays,
      repaymentGraceDays: repaymentGraceDays,
      contributionsAreNonRefundable: contributionsAreNonRefundable,
      displayStatusLabel: displayStatusLabel,
      projectLifecycleState: projectLifecycleState,
      projectBannerStatus: projectBannerStatus,
      votingStatus: votingStatus,
      detailUserRole: detailUserRole,
      voting: voting,
      hasWeek11ProjectDetailEnvelope: hasWeek11ProjectDetailEnvelope,
      apiCanStopContributions: apiCanStopContributions,
      borrowingEnabled: borrowingEnabled,
      pendingJoinRequestCount: pendingJoinRequestCount,
      projectInviteCode: projectInviteCode,
      roiPercentage: roiPercentage,
      joinApprovalRequired: joinApprovalRequired,
      minimumContributionAmount: minimumContributionAmount,
      penaltyPercentage: penaltyPercentage,
      successVoteWindowHours: successVoteWindowHours,
      hasActiveSuccessVote: hasActiveSuccessVote,
      activeClosureVote: activeClosureVote,
      invites: invites,
      hasCoLeader: hasCoLeader,
      coverImageUrl: coverImageUrl,
      images: images,
      membersPagination: membersPagination,
      invitesPagination: invitesPagination,
      announcementsPagination: pagination,
    );
  }

  /// Applies `GET /projects/{id}/pot` (or SignalR payload) to raised amount only.
  /// VFF state comes from `GET /projects/{id}` members — not pot.
  ProjectDetailEntity withProjectPot(ProjectPotEntity pot) {
    final raised = pot.potAmount > 0 ? pot.potAmount : currentAmount;

    return ProjectDetailEntity(
      id: id,
      name: name,
      category: category,
      status: status,
      goalAmount: goalAmount,
      currentAmount: raised,
      totalContributed: totalContributed,
      viewerRefundAmount: viewerRefundAmount,
      contributorCount: pot.contributorCount,
      endsIn: endsIn,
      announcement: announcement,
      announcements: announcements,
      members: members,
      borrowRequests: borrowRequests,
      viewerRole: viewerRole,
      membershipId: membershipId,
      borrowLimitAmount: borrowLimitAmount,
      repaymentWindowDays: repaymentWindowDays,
      repaymentGraceDays: repaymentGraceDays,
      contributionsAreNonRefundable: contributionsAreNonRefundable,
      displayStatusLabel: displayStatusLabel,
      projectLifecycleState: projectLifecycleState,
      projectBannerStatus: projectBannerStatus,
      votingStatus: votingStatus,
      detailUserRole: detailUserRole,
      voting: voting,
      hasWeek11ProjectDetailEnvelope: hasWeek11ProjectDetailEnvelope,
      apiCanStopContributions: apiCanStopContributions,
      borrowingEnabled: borrowingEnabled,
      pendingJoinRequestCount: pendingJoinRequestCount,
      projectInviteCode: projectInviteCode,
      roiPercentage: roiPercentage,
      joinApprovalRequired: joinApprovalRequired,
      minimumContributionAmount: minimumContributionAmount,
      penaltyPercentage: penaltyPercentage,
      successVoteWindowHours: successVoteWindowHours,
      hasActiveSuccessVote: hasActiveSuccessVote,
      activeClosureVote: activeClosureVote,
      invites: invites,
      hasCoLeader: hasCoLeader,
      coverImageUrl: coverImageUrl,
      images: images,
      membersPagination: membersPagination,
      invitesPagination: invitesPagination,
      announcementsPagination: announcementsPagination,
    );
  }

  ProjectDetailEntity withRealtimePotHint({
    required String projectId,
    double? potAmount,
    int? contributorCount,
  }) {
    if (id != projectId) return this;
    if (potAmount == null || potAmount <= 0) return this;
    return ProjectDetailEntity(
      id: id,
      name: name,
      category: category,
      status: status,
      goalAmount: goalAmount,
      currentAmount: potAmount,
      totalContributed: totalContributed,
      viewerRefundAmount: viewerRefundAmount,
      contributorCount: contributorCount ?? this.contributorCount,
      endsIn: endsIn,
      announcement: announcement,
      announcements: announcements,
      members: members,
      borrowRequests: borrowRequests,
      viewerRole: viewerRole,
      membershipId: membershipId,
      borrowLimitAmount: borrowLimitAmount,
      repaymentWindowDays: repaymentWindowDays,
      repaymentGraceDays: repaymentGraceDays,
      contributionsAreNonRefundable: contributionsAreNonRefundable,
      displayStatusLabel: displayStatusLabel,
      projectLifecycleState: projectLifecycleState,
      projectBannerStatus: projectBannerStatus,
      votingStatus: votingStatus,
      detailUserRole: detailUserRole,
      voting: voting,
      hasWeek11ProjectDetailEnvelope: hasWeek11ProjectDetailEnvelope,
      apiCanStopContributions: apiCanStopContributions,
      borrowingEnabled: borrowingEnabled,
      pendingJoinRequestCount: pendingJoinRequestCount,
      projectInviteCode: projectInviteCode,
      roiPercentage: roiPercentage,
      joinApprovalRequired: joinApprovalRequired,
      minimumContributionAmount: minimumContributionAmount,
      penaltyPercentage: penaltyPercentage,
      successVoteWindowHours: successVoteWindowHours,
      hasActiveSuccessVote: hasActiveSuccessVote,
      activeClosureVote: activeClosureVote,
      invites: invites,
      hasCoLeader: hasCoLeader,
      coverImageUrl: coverImageUrl,
      images: images,
      membersPagination: membersPagination,
      invitesPagination: invitesPagination,
      announcementsPagination: announcementsPagination,
    );
  }
}
